More installer work

diff --git a/install b/install
--- a/install
+++ b/install
@@ -2,6 +2,8 @@
 INSTALL_DIR="${HOME}/.shell"
 BACKUP_DIR="${INSTALL_DIR}/backup"
 TARBALL_URL="https://api.github.com/repos/djlambert/shell-profile/tarball/master"
+INSTALL_FILES="profile bashrc dir_colors vimrc"
+TIMESTAMP=$(date +%Y%m%d%H%M%S)
 DEBUG=1
 
 trap cancel INT
@@ -63,7 +65,7 @@ fi
 
 trap cleanUp TERM EXIT
 
-printf "Downloading installation files...\n"
+printf "Downloading package files...\n"
 
 wget --no-verbose --no-check-certificate --output-document=- "${TARBALL_URL}" 2>&4 | tar -xzf- -C "${INSTALL_DIR}" --strip-components=1 1>&3 2>&4
 
@@ -72,3 +74,25 @@ if [ $? -ne 0 ]; then
     exit 1
 fi
 
+mkdir "${BACKUP_DIR}" 1>&3 2>&4
+
+if [ $? -ne 0 ]; then
+    printf "Aborting install, error creating backup directory %s\n" "${INSTALL_DIR}"
+    exit 1
+fi
+
+for basename in $INSTALL_FILES; do
+    # TODO track file operations to allow for error recovery
+    filename=".${basename}"
+    destfile="${HOME}/${filename}"
+    bakfile="${BACKUP_DIR}/${basename}.${TIMESTAMP}"
+
+    if [ -f "${destfile}" ]; then
+        printf "Saving %s to %s\n" "${destfile}" "${bakfile}"
+        mv "${destfile}" "${bakfile}" 1>&3 2>&4
+    fi
+
+    printf "Installing ${basename}\n"
+
+    cp "${INSTALL_DIR}/${basename}" "${destfile}"
+done
