Try again and add error check

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,8 +1,8 @@
 #!/bin/sh
-TARBALL_FILENAME=".shell-profile_${RANDOM}${RANDOM}.tgz"
 INSTALL_DIR="${HOME}/.shell"
 BACKUP_DIR="${INSTALL_DIR}/backup"
 TARBALL_URL="https://api.github.com/repos/djlambert/shell-profile/tarball/master"
+TARBALL_FILE="${INSTALL_DIR}/.shell-profile_${RANDOM}${RANDOM}.tgz"
 BOOTSTRAP_FILES="profile bashrc"
 INSTALL_FILES="dir_colors vimrc"
 INSTALL_FORCE=0
@@ -62,11 +62,11 @@ cleanUp() {
             printf "Removing install directory\n"
             rm -rf "${INSTALL_DIR}" 1>&3 2>&4
         fi
+    fi
 
-        if [ -f "${TARBALL_FILENAME}" ]; then
-            printf "Removing tarball\n"
-            rm "${TARBALL_FILENAME}"
-        fi
+    if [ -f "${TARBALL_FILE}" ]; then
+        printf "Removing tarball\n"
+        rm "${TARBALL_FILE}"
     fi
 
     ioCloseAndExit
@@ -134,14 +134,19 @@ fi
 if [ ${INSTALL_LOCAL:-0} -ne 1 ]; then
     printf "Downloading package files...\n"
 
-    wget --no-verbose --no-check-certificate --output-document="${TARBALL_FILENAME}" "${TARBALL_URL}" 2>&4
+    wget --no-verbose --no-check-certificate --output-document="${TARBALL_FILE}" "${TARBALL_URL}" 2>&4
 
     if [ $? -ne 0 ]; then
         printf "Aborting install, error downloading installation files\n"
         exit 1
     fi
 
-    tar -xzC "${INSTALL_DIR}" --strip-components=1 -f "${TARBALL_FILENAME}" 1>&3 2>&4
+    tar -xz --strip-components=1 -f "${TARBALL_FILE}" 1>&3 2>&4
+
+    if [ $? -ne 0 ]; then
+        printf "Aborting install, error extracting installation files\n"
+        exit 1
+    fi
 else
     printf "Installing from local source\n"
     cp * "${INSTALL_DIR}"
