Use curl if no wget. Other cleanup

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,14 +1,14 @@
 #!/bin/sh
 INSTALL_DIR="${HOME}/.shell"
 BACKUP_DIR="${INSTALL_DIR}/backup"
-TARBALL_URL="https://api.github.com/repos/djlambert/shell-profile/tarball/master"
+TARBALL_URL='https://api.github.com/repos/djlambert/shell-profile/tarball/master'
 TARBALL_FILE=".shell-profile_${RANDOM}${RANDOM}.tgz"
-PATH_FILE_BASE="paths.local"
+PATH_FILE_BASE='paths.local'
 PATH_FILE_LEGACY="${INSTALL_DIR}/${PATH_FILE_BASE}"
 PATH_FILE_PREPEND="${PATH_FILE_LEGACY}.prepend"
 VAR_FILE_LOCAL="${INSTALL_DIR}/vars.local"
-BOOTSTRAP_FILES="profile bashrc"
-INSTALL_FILES="dir_colors vimrc"
+BOOTSTRAP_FILES='profile bashrc'
+INSTALL_FILES='dir_colors vimrc'
 INSTALL_FORCE=0
 INSTALL_LOCAL=0
 INSTALL_EXISTING=0
@@ -18,7 +18,7 @@ DEBUG=1
 RESULT=0
 
 cancel() {
-    printf "Cancelling...\n"
+    printf 'Cancelling...\n'
 }
 
 ioOpen() {
@@ -34,14 +34,13 @@ ioClose() {
 ioCopyStd() {
     exec 3>&1
     exec 4>&2
-
 }
 
 checkDebug() {
     if [ $((${DEBUG:-0})) -eq 1 ]; then
         ioCopyStd
 
-        printf "Debugging enabled\n"
+        printf 'Debugging enabled\n'
     fi
 }
 
@@ -49,7 +48,7 @@ ioCloseAndExit() {
     LAST_RESULT=$?
 
     if [ -z $RESULT ]; then
-        $RESULT=$LAST_RESULT
+        RESULT=$LAST_RESULT
     fi
 
     ioClose
@@ -80,16 +79,16 @@ cleanUp() {
     RESULT=$?
 
     if [ $RESULT -ne 0 ] && [ ${INSTALL_EXISTING:-0} -ne 1 ]; then
-        printf "Cleaning up...\n"
+        printf 'Cleaning up...\n'
 
         if [ -d "${INSTALL_DIR}" ]; then
-            printf "Removing install directory\n"
+            printf 'Removing install directory\n'
             rm -rf "${INSTALL_DIR}" 1>&3 2>&4
         fi
     fi
 
     if [ -f "${TARBALL_FILE}" ]; then
-        printf "Removing tarball\n"
+        printf 'Removing tarball\n'
         rm "${TARBALL_FILE}"
     fi
 
@@ -113,7 +112,7 @@ while getopts i:flp opt; do
         l) INSTALL_LOCAL=1;;         # Use current directory as install source
         p) INSTALL_SAVE_PATH=0;;     # Save existing $PATH
         ?)
-            printf "Usage: %s: [-f][-l][-p][-i install dir]\n" $0
+            printf 'Usage: %s: [-f][-l][-p][-i install dir]\n' "$0"
             exit 2
             ;;
     esac
@@ -122,18 +121,16 @@ done
 # Create install directory
 # Exit with error on failure or directory exists and not force install
 if [ -d "${INSTALL_DIR}" ]; then
-    if [ ${INSTALL_FORCE:-0} -ne 1 ]; then
+    if [ ${INSTALL_FORCE:-0} ]; then
         printf "Aborting install, directory %s already exists\n" "${INSTALL_DIR}"
         exit 1
     else
         INSTALL_EXISTING=1
-        printf "Installing over existing files in %s\n" "${INSTALL_DIR}"
+        printf 'Installing over existing files in %s\n' "${INSTALL_DIR}"
     fi
 else
-    mkdir "${INSTALL_DIR}" 1>&3 2>&4
-
-    if [ $? -ne 0 ]; then
-        printf "Aborting install, error creating directory %s\n" "${INSTALL_DIR}"
+    if ! mkdir "${INSTALL_DIR}" 1>&3 2>&4; then
+        printf 'Aborting install, error creating directory %s\n' "${INSTALL_DIR}"
         exit 1
     fi
 fi
@@ -149,14 +146,14 @@ if [ ! -d "${BACKUP_DIR}" ]; then
     mkdir "${BACKUP_DIR}" 1>&3 2>&4
 
     if [ $? -ne 0 ]; then
-        printf "Aborting install, error creating backup directory %s\n" "${INSTALL_DIR}"
+        printf 'Aborting install, error creating backup directory %s\n' "${INSTALL_DIR}"
         exit 1
     fi
 fi
 
 # Determine tar executable
-if [ $(uname) = "SunOS" ]; then
-    printf "Detected SunOS\n"
+if [ "$(uname)" = 'SunOS' ]; then
+    printf 'Detected SunOS\n'
     TAR_CMD="gtar"
 else
     TAR_CMD="tar"
@@ -165,41 +162,46 @@ fi
 # Download package files
 # Continue on local install source
 if [ ${INSTALL_LOCAL:-0} -ne 1 ]; then
-    printf "Downloading package files...\n"
+    printf 'Downloading package files...\n'
 
-    wget --no-verbose --no-check-certificate --output-document="${TARBALL_FILE}" "${TARBALL_URL}" 2>&4
-
-    if [ $? -ne 0 ]; then
-        printf "Aborting install, error downloading installation files\n"
+    if command wget >/dev/null; then
+        getCommand="wget --no-verbose --no-check-certificate --output-document=${TARBALL_FILE} ${TARBALL_URL}"
+    elif command curl >/dev/null; then
+        getCommand="curl --silent --fail --insecure --output=${TARBALL_FILE} ${TARBALL_URL}"
+    else
+        printf 'Aborting install, wget or curl not found\n'
         exit 1
     fi
 
-    ${TAR_CMD} -xzC "${INSTALL_DIR}" --strip-components=1 -f "${TARBALL_FILE}" 1>&3 2>&4
+    if ! ${getCommand} 2>&4; then
+        printf 'Aborting install, error downloading installation files\n'
+        exit 1
+    fi
 
-    if [ $? -ne 0 ]; then
-        printf "Aborting install, error extracting installation files\n"
+    if ! ${TAR_CMD} -xzC "${INSTALL_DIR}" --strip-components=1 -f "${TARBALL_FILE}" 1>&3 2>&4; then
+        printf 'Aborting install, error extracting installation files\n'
         exit 1
     fi
 else
-    printf "Installing from local source\n"
-    cp * "${INSTALL_DIR}"
+    printf 'Installing from local source\n'
+    cp ./* "${INSTALL_DIR}"
 fi
 
 # Install bootstrap files
 # Create backup if non-bootstrap exists
 for basename in $BOOTSTRAP_FILES; do
     filename=".${basename}"
-    destfile="${HOME}/${filename}"
-    bakfile="${BACKUP_DIR}/${basename}.${TIMESTAMP}"
+    destFile="${HOME}/${filename}"
+    bakFile="${BACKUP_DIR}/${basename}.${TIMESTAMP}"
 
-    if [ -f "${destfile}" ] && [ $(grep -q 'shell-profile-bootstrap' ${destfile}; echo $?) != "0" ]; then
-        printf "Saving %s to %s\n" "${destfile}" "${bakfile}"
-        mv "${destfile}" "${bakfile}" 1>&3 2>&4
+    if [ -f "${destFile}" ] && ! grep -q 'shell-profile-bootstrap' "${destFile}"; then
+        printf 'Saving %s to %s\n' "${destFile}" "${bakFile}"
+        mv "${destFile}" "${bakFile}" 1>&3 2>&4
     fi
 
-    printf "Bootstrapping ${basename}\n"
+    printf 'Bootstrapping %s\n' "${basename}"
 
-    sed "s|##INSTALL##|$INSTALL_DIR|;s|##SCRIPT##|${basename}|" "${INSTALL_DIR}/bootstrap" > "${destfile}"
+    sed "s|##INSTALL##|$INSTALL_DIR|;s|##SCRIPT##|${basename}|" "${INSTALL_DIR}/bootstrap" > "${destFile}"
 done
 
 # Copy additional files
@@ -208,38 +210,38 @@ done
 for basename in $INSTALL_FILES; do
     # TODO track file operations to allow for error recovery in cleanup
     filename=".${basename}"
-    destfile="${HOME}/${filename}"
-    bakfile="${BACKUP_DIR}/${basename}.${TIMESTAMP}"
+    destFile="${HOME}/${filename}"
+    bakFile="${BACKUP_DIR}/${basename}.${TIMESTAMP}"
 
-    if [ -f "${destfile}" ] && [ $(grep -q 'shell-profile-file' ${destfile}; echo $?) != "0" ]; then
-        printf "Saving %s to %s\n" "${destfile}" "${bakfile}"
-        mv "${destfile}" "${bakfile}" 1>&3 2>&4
+    if [ -f "${destFile}" ] && ! grep -q 'shell-profile-bootstrap' "${destFile}"; then
+        printf 'Saving %s to %s\n' "${destFile}" "${bakFile}"
+        mv "${destFile}" "${bakFile}" 1>&3 2>&4
     fi
 
-    printf "Installing ${basename}\n"
+    printf 'Installing %s\n' "${basename}"
 
-    cp "${INSTALL_DIR}/${basename}" "${destfile}"
+    cp "${INSTALL_DIR}/${basename}" "${destFile}"
 done
 
 # Migrate old paths.local file
 if [ -f "${PATH_FILE_LEGACY}" ]; then
-    bakfile="${BACKUP_DIR}/${PATH_FILE_BASE}.${TIMESTAMP}"
-    printf "Moving legacy paths from %s to %s\n" "${PATH_FILE_LEGACY}" "${PATH_FILE_PREPEND}"
+    bakFile="${BACKUP_DIR}/${PATH_FILE_BASE}.${TIMESTAMP}"
+    printf 'Moving legacy paths from %s to %s\n' "${PATH_FILE_LEGACY}" "${PATH_FILE_PREPEND}"
     cat "${PATH_FILE_LEGACY}" >> "${PATH_FILE_PREPEND}"
-    printf "Moving legacy paths file to %s\n" "${bakfile}"
-    mv "${PATH_FILE_LEGACY}" "${bakfile}"
+    printf 'Moving legacy paths file to %s\n' "${bakFile}"
+    mv "${PATH_FILE_LEGACY}" "${bakFile}"
 fi
 
 if [ "${INSTALL_SAVE_PATH}" -ne 1 ]; then
-    printf "Skipping saving existing path\n"
+    printf 'Skipping saving existing path\n'
 else
-    findSetting "PATH" "${VAR_FILE_LOCAL}" >/dev/null
+    findSetting 'PATH' "${VAR_FILE_LOCAL}" >/dev/null
 
     if [ $? -ne 0 ]; then
-        printf "PATH already in %s\n" "${VAR_FILE_LOCAL}"
+        printf 'PATH already in %s\n' "${VAR_FILE_LOCAL}"
     else
-        printf "Saving current path in %s\n" "${VAR_FILE_LOCAL}"
-        printf "PATH=%s\n" "${PATH}" >> "${VAR_FILE_LOCAL}"
+        printf 'Saving current path in %s\n' "${VAR_FILE_LOCAL}"
+        printf 'PATH=%s\n' "${PATH}" >> "${VAR_FILE_LOCAL}"
     fi
 fi
 # vim: syntax=sh:ts=4:sw=4
